[package]
name = "worklog"
version.workspace = true
edition.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-autostart = "2"
tauri-plugin-single-instance = "2"
chrono = "0.4"
worklog-core = { path = "../crates/worklog-core" }
serde = { version = "1", features = ["derive"] }
