[package]
name = "worklog"
version = "0.1.1"
edition = "2024"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-autostart = "2"
tauri-plugin-single-instance = "2"
chrono = "0.4"
fetch-focused-window = { path = ".." }
serde = { version = "1", features = ["derive"] }
